-- Initial migration. Generated to make the schema reproducible; run `npx prisma migrate deploy` after installing dependencies.
CREATE TYPE "Role" AS ENUM ('USER','MODERATOR','ADMIN','SUPER_ADMIN');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','SUSPENDED','BANNED');
CREATE TYPE "GameMode" AS ENUM ('ONLINE','BOT');
CREATE TYPE "GameStatus" AS ENUM ('CREATED','WAITING','ACTIVE','FINISHED','ABORTED','ARCHIVED');
CREATE TYPE "GameResult" AS ENUM ('WHITE','BLACK','DRAW');
CREATE TYPE "MatchStatus" AS ENUM ('SEARCHING','MATCHED','CANCELLED','EXPIRED');
CREATE TYPE "DrawStatus" AS ENUM ('OFFERED','ACCEPTED','DECLINED');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"username" TEXT NOT NULL UNIQUE,"email" TEXT NOT NULL UNIQUE,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'USER',"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Profile" ("userId" TEXT PRIMARY KEY,"displayName" TEXT,"avatarUrl" TEXT,"bio" TEXT);
CREATE TABLE "Rating" ("userId" TEXT PRIMARY KEY,"mode" TEXT NOT NULL DEFAULT 'blitz',"rating" INTEGER NOT NULL DEFAULT 1200,"peakRating" INTEGER NOT NULL DEFAULT 1200);
CREATE TABLE "Game" ("id" TEXT PRIMARY KEY,"mode" "GameMode" NOT NULL,"status" "GameStatus" NOT NULL DEFAULT 'CREATED',"timeControl" TEXT NOT NULL,"initialSeconds" INTEGER NOT NULL,"incrementSeconds" INTEGER NOT NULL,"whitePlayerId" TEXT,"blackPlayerId" TEXT,"result" "GameResult","resultReason" TEXT,"initialFen" TEXT NOT NULL,"finalFen" TEXT,"pgn" TEXT,"startedAt" TIMESTAMP(3),"endedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "GameMove" ("id" TEXT PRIMARY KEY,"gameId" TEXT NOT NULL,"ply" INTEGER NOT NULL,"moveUci" TEXT NOT NULL,"moveSan" TEXT NOT NULL,"fenAfter" TEXT NOT NULL,"clockWhiteMs" INTEGER NOT NULL,"clockBlackMs" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GameMove_gameId_ply_key" UNIQUE("gameId","ply"));
CREATE TABLE "MatchmakingTicket" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"timeControl" TEXT NOT NULL,"rating" INTEGER NOT NULL,"status" "MatchStatus" NOT NULL DEFAULT 'SEARCHING',"queuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3) NOT NULL,"matchedGameId" TEXT);
CREATE TABLE "DrawOffer" ("id" TEXT PRIMARY KEY,"gameId" TEXT NOT NULL,"offeredBy" TEXT NOT NULL,"status" "DrawStatus" NOT NULL DEFAULT 'OFFERED',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"respondedAt" TIMESTAMP(3));
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3));
CREATE TABLE "Report" ("id" TEXT PRIMARY KEY,"reporterId" TEXT NOT NULL,"reportedUserId" TEXT NOT NULL,"gameId" TEXT,"reason" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AdminAction" ("id" TEXT PRIMARY KEY,"adminId" TEXT NOT NULL,"targetUserId" TEXT,"action" TEXT NOT NULL,"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Notification" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"type" TEXT NOT NULL,"payloadJson" JSONB,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "Profile" ADD CONSTRAINT "Profile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Rating" ADD CONSTRAINT "Rating_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Game" ADD CONSTRAINT "Game_whitePlayerId_fkey" FOREIGN KEY ("whitePlayerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Game" ADD CONSTRAINT "Game_blackPlayerId_fkey" FOREIGN KEY ("blackPlayerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "GameMove" ADD CONSTRAINT "GameMove_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MatchmakingTicket" ADD CONSTRAINT "MatchmakingTicket_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DrawOffer" ADD CONSTRAINT "DrawOffer_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_reportedUserId_fkey" FOREIGN KEY ("reportedUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdminAction" ADD CONSTRAINT "AdminAction_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX "Game_whitePlayerId_endedAt_idx" ON "Game"("whitePlayerId","endedAt");
CREATE INDEX "Game_blackPlayerId_endedAt_idx" ON "Game"("blackPlayerId","endedAt");
CREATE INDEX "MatchmakingTicket_status_timeControl_queuedAt_idx" ON "MatchmakingTicket"("status","timeControl","queuedAt");
